apiVersion: eidolon/v1
kind: Reference
metadata:
  name: RedditSearcher

spec:
  implementation: Search
  name: "search_reddit"
  description: "Searches redit for articles matching the query. Be very specific in the query parameters to get the best results"
  siteSearch: "reddit.com"
