apiVersion: eidolon/v1
kind: Agent
metadata:
  name: LinkedInPulse

spec:
  implementation: WebSearchAgent
  name: "search_linkedin_pulse"
  description: "Searches linkedin pulse articles matching the given criteria. Be very specific in the query parameters to get the best results"
  siteSearch: "linkedin.com/posts"
