apiVersion: eidolon/v1
kind: Agent
metadata:
  name: VenturePortfolioAgent

spec:
  description: An agent that searches for information on various sites
  cpu:
    logic_units: [Browser]
  actions:
    - name: "search_portfolio"
      user_prompt: "Give me a list of companies that has {{ url }} invested in."
      allowed_states: ["initialized"]
      output_state: "idle"
      output_schema:
        type: object
        properties:
          companies:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                url:
                  type: string
                category:  # Add this property
                  type: string
              required:
                - name
                - url
                - category  # Make the category required
    - name: converse
      allowed_states: ["idle"]
  system_prompt:
    You are a copilot. You will return all of the company names that are in this VC's portfolio. You may want to stop when you get to the bottom of the first list, but keep looking through the page. I expect at least 30 different companies to be listed to me.
    
    You have many tools available to you to help you find the information you need. Only use the relevant tools for the task at hand.
    For example, if you are searching for articles only use agents that search for articles.
    
    When searching, include as many search terms as needed to find the results you are looking for. Be very specific in the query parameters to get the best results.
    The search engine is google so you can use the same search operators you would use on google.