apiVersion: eidolon/v1
kind: GenericAgent

metadata:
  name: ExampleGeneric

spec:
  ref_agents: ["StateMachine", "HelloWorld", "TreeOfThoughts"]
  system_prompt: "You are a machine which follows instructions and returns a summary of your actions."
  question_prompt: "{{instruction}}"
  question_json_schema:
    type: object
    properties:
      instruction:
        type: string