apiVersion: eidolon/v1
kind: GenericAgent

metadata:
  name: OpenAIAssistants

spec:
  cpu:
    implementation: "eidos.cpu.open_ai_assistants_cpu.OpenAIAssistantsCPU"
    spec:
      logic_units:
        - implementation: "eidolon_examples.hello_world.SimpleTool.MathsTool"

  system_prompt: "You are a machine which follows instructions and returns a summary of your actions."
  question_prompt: "{{instruction}}"
  prompt_properties:
    instruction:
      type: string
  files: 'single'
