apiVersion: eidolon/v1
kind: TreeOfThoughtsAgent

metadata:
  name: TreeOfThoughts

spec:
  description: "This is an example of a generic agent which can be used to create a conversational agent."
  fallback: LLM
  user_prompt: "{{question}}"
  input_schema:
    question:
      type: string
  output_schema: 'str'
