[tool.poetry]
name = "sdk"
version = "0.1.0"
description = ""
authors = ["Luke Lalor <lukehlalor@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
setuptools = "^68.2.2"
fastapi = "^0.104.1"
pyyaml = "^6.0.1"
jsonschema = "^4.19.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
