agent_memory:
  file_memory:
    implementation: "eidolon_sdk.impl.local_file_memory.LocalFileMemory"
    spec:
      root_dir: "/tmp/hello_world"
  symbolic_memory:
    implementation: "eidolon_sdk.impl.mongo_symbolic_memory.MongoSymbolicMemory"
    spec:
      mongo_database_name: "eidolon"
  similarity_memory:
    implementation: "eidolon_sdk.impl.noop_memory.NoopSimilarityMemory"

agent_programs:
  ExampleAuto:
    agent:
      implementation: "examples.hello_world.AutonomousAgent.AutonomousAgent"
  ExampleAgentProgram:
    agent:
      implementation: "examples.hello_world.HelloWorld.HelloWorld"
  StateMachine:
    agent:
      implementation: "examples.hello_world.StateMachine.StateMachine"
