agent_memory:
  file_memory:
    implementation: "eidolon_sdk.impl.memory.local_file_memory.LocalFileMemory"
    spec:
      root_dir: "/tmp/hello_world"
  symbolic_memory:
    implementation: "eidolon_sdk.impl.memory.mongo_symbolic_memory.MongoSymbolicMemory"
    spec:
      mongo_database_name: "eidolon"
  similarity_memory:
    spec:
      vector_store:
        implementation: "eidolon_sdk.impl.memory.noop_memory.NoopVectorStore"

agent_programs:
  TreeOfThoughts:
    agent:
      implementation: "eidolon_sdk.impl.tot_agent.tot_agent.TreeOfThoughtsAgent"
      spec:
        fallback: LLM
        question_prompt: "{{question}}"
        question_json_schema:
          type: object
          properties:
            question:
              type: string

#  todo, back generic agent cpu by tree of thoughts
  ExampleGeneric:
    agent:
      implementation: "eidolon_sdk.impl.generic_agent.GenericAgent"
      spec:
        system_prompt: "You are a machine which follows instructions and returns a summary of your actions."
        question_prompt: "{{instruction}}"
        question_json_schema:
          type: object
          properties:
              instruction:
                type: string
    cpu:
      spec:
        logic_units:
          - implementation: "eidolon_sdk.impl.cpu.conversational_logic_unit.ConversationalLogicUnit"
            spec:
              agents: ["StateMachine", "ExampleAgentProgram", "TreeOfThoughts"]

  ExampleAuto:
    agent:
      implementation: "examples.hello_world.AutonomousAgent.AutonomousAgent"

#  ExampleCustomSummarizer:
#    agent:
#      implementation: "examples.hello_world.AutonomousAgent.AutonomousAgent"
#    cpu:
#      memory_unit:
#        implementation: "eidolon_sdk.impl.summarization_memory_unit.SummarizationMemoryUnit"
#        spec:
#          max_token_fraction: 0.005
#          summarizer:
#              implementation: "examples.hello_world.CustomSummary.CustomSummarizer"
#      llm_unit:
#        implementation: "eidolon_sdk.impl.open_ai_llm_unit.OpenAIGPT"
#        spec:
#          model: "gpt-4-1106-preview"
#          temperature: 0.3

  ExampleAgentProgram:
    agent:
      implementation: "examples.hello_world.HelloWorld.HelloWorld"
  StateMachine:
    agent:
      implementation: "examples.hello_world.StateMachine.StateMachine"
