agent_memory:
  file_memory:
    implementation: "eidolon_sdk.impl.local_file_memory.LocalFileMemory"
    spec:
      root_dir: "/tmp/hello_world"
  symbolic_memory:
    implementation: "eidolon_sdk.impl.mongo_symbolic_memory.MongoSymbolicMemory"
    spec:
      mongo_database_name: "eidolon"
  similarity_memory:
    implementation: "eidolon_sdk.impl.noop_memory.NoopSimilarityMemory"

agent_programs:
  ExampleGeneric:
    agent:
      implementation: "eidolon_sdk.impl.generic_agent.GenericAgent"
      spec:
        system_prompt: "You are an angry sailor. You are in a bar. You are looking for a fight. A user walks in and orders a {{drink_order}}."
        question_prompt: "How do you do? My name is {{name}}. {{statement}}"
        question_json_schema:
          type: object
          properties:
              name:
                type: string
              drink_order:
                type: string
              statement:
                type: string
    cpu:
      io_unit:
        implementation: "eidolon_sdk.cpu.agent_io.IOUnit"
        spec:
          io_write: "Request"
          io_read: "Response"
      memory_unit:
        implementation: "eidolon_sdk.impl.conversation_memory_unit.ConversationalMemoryUnit"
        spec:
          msf_read: "Request"
          msf_write: "Conversation"
      llm_unit:
        implementation: "eidolon_sdk.impl.open_ai_llm_unit.OpenAIGPT"
        spec:
          model: "gpt-4-1106-preview"
          temperature: 0.3
          llm_read: "Conversation"
          llm_write: "Response"

  ExampleAuto:
    agent:
      implementation: "examples.hello_world.AutonomousAgent.AutonomousAgent"
    cpu:
      io_unit:
        implementation: "eidolon_sdk.cpu.agent_io.IOUnit"
        spec:
          io_write: "Request"
          io_read: "Response"
      memory_unit:
        implementation: "eidolon_sdk.impl.conversation_memory_unit.ConversationalMemoryUnit"
        spec:
          msf_read: "Request"
          msf_write: "Conversation"
      llm_unit:
        implementation: "eidolon_sdk.impl.open_ai_llm_unit.OpenAIGPT"
        spec:
          model: "gpt-4-1106-preview"
          temperature: 0.3
          llm_read: "Conversation"
          llm_write: "Response"

  ExampleAgentProgram:
    agent:
      implementation: "examples.hello_world.HelloWorld.HelloWorld"
  StateMachine:
    agent:
      implementation: "examples.hello_world.StateMachine.StateMachine"
