agent_programs:
  - name: "ExampleAgentProgram"
    implementation: "examples.hello_world.HelloWorld.HelloWorld"
    initial_state: "idle"
    states:
      idle:
        state_name: "idle"
        description: "This is the starting state of the agent program."
        transitions_to:
          idle:
            description: "The welcome message is printed."
            type: "object"
            properties:
              welcome_message:
                type: "string"
