agent_memory:
  file_memory:
    implementation: "eidolon_sdk.impl.local_file_memory.LocalFileMemory"
    root_dir: "${EIDOLON_DATA_DIR}/hello_world"
  symbolic_memory:
    implementation: "eidolon_sdk.impl.mongo_symbolic_memory.MongoSymbolicMemory"
    mongo_database_name: "eidolon"
  similarity_memory:
    implementation: "eidolon_sdk.impl.noop_memory.NoopSimilarityMemory"

agent_programs:
  - name: "ExampleAgentProgram"
    implementation: "examples.hello_world.HelloWorld.HelloWorld"
    initial_state: "idle"
